### ISSUE TITLE
Help!

### ISSUE THREAD

**Issue by jimbok8** [Legioth/splash-screen#7]
This looks really interesting, but I am so new to Vaddin that I have no idea how to use it!
I have a demo application (Vaadin flow 14) with a MainView class and an Application class.

Please can you tell me how I would implement your splash-screen with these two classes?
Thanks
Jim

(MainView extends Composite<VerticalLayout> )

**Comment by Legioth** [comment]
This add-on is implemented only for Vaadin 8.

Back in the days, I tried to get the same basic idea working with Vaadin 10, but there were some issues then with regards to rendering being blocked in some browsers so that the splash screen was shown too late. There is a possibility that the switch from HTML imports to JS modules that happened in Vaadin 14 would have an impact on this, but I haven't investigated that possibility. You can follow https://github.com/Legioth/splash-screen/issues/8 if you want to get updates if I get some inspiration to further investigate this.
